name: Test Deno Library Data.Either

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-version: [1.3.2]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Deno Version ${{ matrix.deno-version }}
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: Lint Data.Either
        run: deno fmt --check
      - name: Build Data.Either
        run: deno run --reload mod.ts
      - name: Test Data.Either
        run: deno test --allow-none
